### ISSUE TITLE
getLyrics() returns an empty array

### ISSUE THREAD

**Issue by Garlicvideos** [farshed/genius-lyrics-api#1]
## Issue
The getLyrics() method returns an empty array instead of null for certain songs.

## Steps to reproduce
Set these as the options for search:

`{ apiKey: 'APIKEY',
  title: 'DESPACITO',
  artist: 'LUIS%20FONSI%20FT.%20JUSTIN%20BIEBER',
  optimizeQuery: true }`

## Details
getLyrics() works for many other songs that I try, including the example song shown in the readme. So far, this is the only song that has gone through the method to have returned an empty array instead of a string or a null value.

**Comment by farshed** [comment]
@Garlicvideos I found the problem. Genius seems to be returning the link to a weird webpage that the package can't parse. So it returns an empty string, not an array.

**What the package expects:** https://genius.com/Luis-fonsi-despacito-lyrics
**OR** https://genius.com/Luis-fonsi-and-daddy-yankee-despacito-remix-lyrics

**What Genius api returns:** https://genius.com/Fuis-lonsi-despacitwo-lyrics

I'll patch it and push a release in the morning so that it returns null in such cases.
